/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;

import java.util.Map;
import java.util.HashMap;

import spark.ModelAndView;
import static spark.Spark.*;
import spark.template.handlebars.HandlebarsTemplateEngine;

public class App {

	public String getGreeting() {
        return "Hello Ginger.";
    }

    public static void main(String[] args) throws Exception {
      DB db = new DB();
      db.connect();
	    // System.out.println(new App().getGreeting());
       //UserAdmin.demo();
	String portString = System.getenv("JETTY_PORT");
	if (portString == null || portString.equals(""))
		port (5000);	
    	else
		port(Integer.parseInt(portString));
	//  port(5000);
  //  	    get("/hello", (req, res) -> "Hello World");

//	get("/goodbye", (req, rest) -> "Goodbye");

//	get("/greet/:name", (req, res) -> {
//		return "Hello " + req.params(":name");
//	});
	//String result = db.listUsers();
//	System.out.println(result);	
	new Admin().addRoutes();
    }
}
