/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package edu.au.cc.gallery;

public class App {
    public String getGreeting() {
        return "Hello Ginger.";
    }

    public static void main(String[] args) throws Exception {
       // System.out.println(new App().getGreeting());
       UserAdmin.demo();
    }
}
